<a href="https://colab.research.google.com/github/calderon-caylie/Data_Analysis_Capstone/blob/main/Colab_EDA_For_Capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Caylie-Mackay/Raw_CSV/refs/heads/main/bike_sales_100k.csv')
df.head()

,Sale_ID,Date,Customer_ID,Bike_Model,Price,Quantity,Store_Location,Salesperson_ID,Payment_Method,Customer_Age,Customer_Gender
0,1,11-07-2022,9390,Cruiser,318.32,1,Philadelphia,589,Apple Pay,70,Female
1,2,03-05-2024,3374,Hybrid Bike,3093.47,4,Chicago,390,Apple Pay,37,Male
2,3,01-09-2022,2689,Folding Bike,4247.99,3,San Antonio,338,PayPal,59,Female
3,4,28-09-2022,3797,Mountain Bike,1722.01,3,San Antonio,352,Apple Pay,19,Male
4,5,05-01-2021,1633,BMX,3941.44,3,Philadelphia,580,PayPal,67,Female

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Sale_ID          100000 non-null  int64
 1   Date             100000 non-null  object
 2   Customer_ID      100000 non-null  int64
 3   Bike_Model       100000 non-null  object
 4   Price            100000 non-null  float64
 5   Quantity         100000 non-null  int64
 6   Store_Location   100000 non-null  object
 7   Salesperson_ID   100000 non-null  int64
 8   Payment_Method   100000 non-null  object
 9   Customer_Age     100000 non-null  int64
 10  Customer_Gender  100000 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 8.4+ MB

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Sale_ID          100000 non-null  int64
 1   Date             100000 non-null  object
 2   Customer_ID      100000 non-null  int64
 3   Bike_Model       100000 non-null  object
 4   Price            100000 non-null  float64
 5   Quantity         100000 non-null  int64
 6   Store_Location   100000 non-null  object
 7   Salesperson_ID   100000 non-null  int64
 8   Payment_Method   100000 non-null  object
 9   Customer_Age     100000 non-null  int64
 10  Customer_Gender  100000 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 8.4+ MB

This dataset does not have any duplicates or nulls.

In [ ]:
df.describe()

,Sale_ID,Customer_ID,Price,Quantity,Salesperson_ID,Customer_Age
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,5495.450720,2598.182340,2.997110,549.906300,44.043410
std,28867.657797,2598.873948,1384.943133,1.414235,259.679221,15.313761
min,1.000000,1000.000000,200.010000,1.000000,100.000000,18.000000
25%,25000.750000,3249.000000,1399.787500,2.000000,324.000000,31.000000
50%,50000.500000,5491.000000,2598.575000,3.000000,550.000000,44.000000
75%,75000.250000,7738.000000,3795.982500,4.000000,775.000000,57.000000
max,100000.000000,9999.000000,4999.810000,5.000000,999.000000,70.000000

Some noteable descriptive statistics are the average price of a bike and age of a customer. The min and max of the price also helps us to know the price range of the products.

In [ ]:
Male_vs_female = df.groupby('Customer_Gender')['Customer_Gender'].count().reset_index(name='Count')
Male_vs_female

  Customer_Gender  Count
0          Female  50227
1            Male  49773

In [ ]:
df['Transaction Total'] = df['Quantity'] * df['Price']
df.head()

,Sale_ID,Date,Customer_ID,Bike_Model,Price,Quantity,Store_Location,Salesperson_ID,Payment_Method,Customer_Age,Customer_Gender,Transaction Total
0,1,11-07-2022,9390,Cruiser,318.32,1,Philadelphia,589,Apple Pay,70,Female,318.32
1,2,03-05-2024,3374,Hybrid Bike,3093.47,4,Chicago,390,Apple Pay,37,Male,12373.88
2,3,01-09-2022,2689,Folding Bike,4247.99,3,San Antonio,338,PayPal,59,Female,12743.97
3,4,28-09-2022,3797,Mountain Bike,1722.01,3,San Antonio,352,Apple Pay,19,Male,5166.03
4,5,05-01-2021,1633,BMX,3941.44,3,Philadelphia,580,PayPal,67,Female,11824.32

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df.head()

,Sale_ID,Date,Customer_ID,Bike_Model,Price,Quantity,Store_Location,Salesperson_ID,Payment_Method,Customer_Age,Customer_Gender,Transaction Total
0,1,2022-07-11,9390,Cruiser,318.32,1,Philadelphia,589,Apple Pay,70,Female,318.32
1,2,2024-05-03,3374,Hybrid Bike,3093.47,4,Chicago,390,Apple Pay,37,Male,12373.88
2,3,2022-09-01,2689,Folding Bike,4247.99,3,San Antonio,338,PayPal,59,Female,12743.97
3,4,2022-09-28,3797,Mountain Bike,1722.01,3,San Antonio,352,Apple Pay,19,Male,5166.03
4,5,2021-01-05,1633,BMX,3941.44,3,Philadelphia,580,PayPal,67,Female,11824.32

In [ ]:
df['Year'] = df['Date'].dt.year
avg_total_by_year = df.groupby('Year')['Transaction Total'].mean().reset_index()
avg_total_by_year = avg_total_by_year.round(2)
avg_total_by_year

   Year  Transaction Total
0  2020            7749.73
1  2021            7808.96
2  2022            7789.26
3  2023            7779.50
4  2024            7798.29

In [ ]:
Sales_Goal = avg_total_by_year.copy()
Sales_Goal['Transaction Total'] = Sales_Goal['Transaction Total'] + 100
Sales_Goal

   Year  Transaction Total
0  2020            7849.73
1  2021            7908.96
2  2022            7889.26
3  2023            7879.50
4  2024            7898.29

In [ ]:
employee_sales_by_year = df.groupby(['Year', 'Salesperson_ID'])['Transaction Total'].mean().reset_index()
employee_sales_by_year

      Year  Salesperson_ID  Transaction Total
0     2020             100        9528.349630
1     2020             101        9090.755862
2     2020             102       10307.172353
3     2020             103        9064.142083
4     2020             104        7928.206000
...    ...             ...                ...
4495  2024             995        7833.281667
4496  2024             996        8609.583000
4497  2024             997       10095.525882
4498  2024             998       12479.904444
4499  2024             999       11262.246429

[4500 rows x 3 columns]

In [ ]:
employee_sales_by_year_2021 = employee_sales_by_year[employee_sales_by_year['Year'] == 2021].copy()

sales_goal_2021 = Sales_Goal[Sales_Goal['Year'] == 2020]['Transaction Total'].iloc[0]
employee_sales_by_year_2021['Met Sales Goal'] = np.where(
    employee_sales_by_year_2021['Transaction Total'] >= sales_goal_2021,
    'Goal Met',
    'Under Goal'
)
employee_sales_by_year_2021.head()

     Year  Salesperson_ID  Transaction Total Met Sales Goal
900  2021             100        6161.592800     Under Goal
901  2021             101        9958.667857       Goal Met
902  2021             102        7583.779231     Under Goal
903  2021             103        6700.732917     Under Goal
904  2021             104        6379.449412     Under Goal

In [ ]:
employee_sales_by_year_2021.value_counts('Met Sales Goal')

Met Sales Goal
Under Goal    476
Goal Met      424
Name: count, dtype: int64

In [ ]:
employee_sales_by_year_2022 = employee_sales_by_year[employee_sales_by_year['Year'] == 2022].copy()

sales_goal_2022 = Sales_Goal[Sales_Goal['Year'] == 2021]['Transaction Total'].iloc[0]
employee_sales_by_year_2022['Met Sales Goal'] = np.where(
    employee_sales_by_year_2022['Transaction Total'] >= sales_goal_2022,
    'Goal Met',
    'Under Goal'
)
employee_sales_by_year_2022.head()

      Year  Salesperson_ID  Transaction Total Met Sales Goal
1800  2022             100        8444.758077       Goal Met
1801  2022             101        6990.726250     Under Goal
1802  2022             102        9616.750435       Goal Met
1803  2022             103        7214.530357     Under Goal
1804  2022             104        9122.058696       Goal Met

In [ ]:
employee_sales_by_year_2022.value_counts('Met Sales Goal')

Met Sales Goal
Under Goal    500
Goal Met      400
Name: count, dtype: int64

In [ ]:
employee_sales_by_year_2023 = employee_sales_by_year[employee_sales_by_year['Year'] == 2023].copy()

sales_goal_2023 = Sales_Goal[Sales_Goal['Year'] == 2022]['Transaction Total'].iloc[0]
employee_sales_by_year_2023['Met Sales Goal'] = np.where(
    employee_sales_by_year_2023['Transaction Total'] >= sales_goal_2023,
    'Goal Met',
    'Under Goal'
)
employee_sales_by_year_2023.head()

      Year  Salesperson_ID  Transaction Total Met Sales Goal
2700  2023             100        6653.691724     Under Goal
2701  2023             101        6510.902609     Under Goal
2702  2023             102        8147.592778       Goal Met
2703  2023             103        6962.311500     Under Goal
2704  2023             104        5379.028333     Under Goal

In [ ]:
employee_sales_by_year_2023.value_counts('Met Sales Goal')

Met Sales Goal
Under Goal    489
Goal Met      411
Name: count, dtype: int64

In [ ]:
employee_sales_by_year_2024 = employee_sales_by_year[employee_sales_by_year['Year'] == 2024].copy()

sales_goal_2024 = Sales_Goal[Sales_Goal['Year'] == 2023]['Transaction Total'].iloc[0]
employee_sales_by_year_2024['Met Sales Goal'] = np.where(
    employee_sales_by_year_2024['Transaction Total'] >= sales_goal_2024,
    'Goal Met',
    'Under Goal'
)
employee_sales_by_year_2024.head()

      Year  Salesperson_ID  Transaction Total Met Sales Goal
3600  2024             100        7624.459583     Under Goal
3601  2024             101       11003.239231       Goal Met
3602  2024             102        8953.373333       Goal Met
3603  2024             103        7060.406154     Under Goal
3604  2024             104        8715.200000       Goal Met

In [ ]:
employee_sales_by_year_2024.value_counts('Met Sales Goal')

Met Sales Goal
Under Goal    506
Goal Met      394
Name: count, dtype: int64

In [ ]:
all_goals = pd.concat([
    employee_sales_by_year_2021[['Year', 'Salesperson_ID', 'Met Sales Goal']],
    employee_sales_by_year_2022[['Year', 'Salesperson_ID', 'Met Sales Goal']],
    employee_sales_by_year_2023[['Year', 'Salesperson_ID', 'Met Sales Goal']],
    employee_sales_by_year_2024[['Year', 'Salesperson_ID', 'Met Sales Goal']]
])

In [ ]:
employee_sales_by_year = pd.merge(
    employee_sales_by_year,
    all_goals,
    on=['Year', 'Salesperson_ID'],
    how='left'
)

employee_sales_by_year

      Year  Salesperson_ID  Transaction Total Met Sales Goal
0     2020             100        9528.349630            NaN
1     2020             101        9090.755862            NaN
2     2020             102       10307.172353            NaN
3     2020             103        9064.142083            NaN
4     2020             104        7928.206000            NaN
...    ...             ...                ...            ...
4495  2024             995        7833.281667     Under Goal
4496  2024             996        8609.583000       Goal Met
4497  2024             997       10095.525882       Goal Met
4498  2024             998       12479.904444       Goal Met
4499  2024             999       11262.246429       Goal Met

[4500 rows x 4 columns]

In [ ]:
employee_sales_by_year = employee_sales_by_year[
    employee_sales_by_year['Year'] != 2020
]
employee_sales_by_year.head()

     Year  Salesperson_ID  Transaction Total Met Sales Goal
900  2021             100        6161.592800     Under Goal
901  2021             101        9958.667857       Goal Met
902  2021             102        7583.779231     Under Goal
903  2021             103        6700.732917     Under Goal
904  2021             104        6379.449412     Under Goal

In [ ]:
df.to_csv('Updated_bike_data.csv')

In [ ]:
employee_sales_by_year.to_csv('Employee_sales_by_year.csv')